pipelines:
  default:
    - step:
        image: python:3.7.8
        name: Python 3.7
        script:
          - pip install -r requirements-dev.txt
          - python setup.py test
    - step:
        image: python:3.6.11
        name: Python 3.6
        script:
          - pip install -r requirements-dev.txt
          - python setup.py test
    - step:
        image: python:3.8.5
        name: Python 3.8
        script:
          - pip install -r requirements-dev.txt
          - python setup.py test
    - step:
        image: python:3.9.7
        name: Python 3.9
        script:
          - pip install -r requirements-dev.txt
          - python setup.py test
    - step:
        image: python:3.10.0
        name: Python 3.10
        script:
          - pip install -r requirements-dev.txt
          - python setup.py test
